name: Continuous Integration
on: [push]

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader
      - name: Run PHPStan analysis
        run: composer phpstan
